name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Install dependencies
      run: go mod tidy  # Ensure dependencies are installed
    - name: Build
      run: go build -v ./...
    - name: function build
      working-directory: function
      run: go build -v ./...
    - name: Run Go tests for function
      working-directory: function
      run: go test -v ./...
    - name: Run Go tests
      # working-directory: function
      run: go test -v ./cmd/gcptool

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'gcloud'

    - name: Build gcptool
      run: go build -v -o gcptool ./cmd/gcptool
      
    - name: Describe deployed function
      run: ./gcptool describe carbonq

    - name: Deploy Function using gcptool
      if: success()
      run: ./gcptool deploy carbonq --source=function -e dev -v v1.0.0 -c
